#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}add${reset} command."

# The command's name
echo -e 'git add'

# the command's description
echo "Used to add files to the Git's staging area. If you want to start tracking any new file (and also to stage changes to already tracked files), you need to add them with ${bold}git add${reset}."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git add [OPTIONS]...${reset}"			
echo -e "\t${bold}-A, --all:${reset} \t Updates all files in the entire working tree."			
echo -e "\t${bold}-n, --dry-run:${reset} \t Don’t actually add the file(s), just show if they exist and/or will be ignored."			
echo -e "\t${bold}-v, --verbose${reset} \t Be verbose."			

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
