#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}branch${reset} command."

# The command's name
echo -e 'git branch'

# the command's description
echo "When used without arguments, it lists all the branches in the current repository. When an argument is provided, it creates a branch with the specified name. Note that this doesn't place you in the branch until you check it out."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git branch <branchname>"
echo "Creates a new branch called <${bold}branchname${reset}>"

# example 2
echo "git branch -d <branchname>"
echo "Deletes the existing branch <${bold}branchname${reset}>"


exit 0
