#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}checkout${reset} command."

# The command's name
echo -e 'git checkout'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git checkout [OPTIONS]${reset}"
echo -e "\t-${bold}b <new_branch>${reset}:\t Specifying -b causes a new branch to be created"
echo -e "\t-${bold}f${reset}:\t When switching branches, proceed even if the index or the working tree differs from HEAD"
echo -e "\t-${bold}t${reset}:\t When creating a new branch, set up "upstream" configuration"

echo "------------"

# the command's usage examples
# example 1
echo "git checkout bug12"
echo "Checks out the branch 'bug12' if it exists."

# example 2
echo "git checkout -b bug12"
echo "Creates the branch 'bug12' and checks it out. "


exit 0
