#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the git ${bold}checkout${reset} command."

# The command's name
echo -e 'git checkout'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git checkout bug12"
echo "Checks out the branch 'bug12' if it exists."

# example 2
echo "git checkout -b bug12"
echo "Creates the branch 'bug12' and checks it out. "


exit 0
