#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the git ${bold}commit${reset} command."

# The command's name
echo -e 'git commit'

# the command's description
echo "Used to record changes (snapshots) to the repository. Snapshots are always committed to the local repository."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git commit [OPTIONS]...${reset}"			
echo -e "\t${bold}-a, --all:${reset} \t Tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected."			
echo -e "\t${bold}-m, --message:${reset} \t Use the given <msg> as the commit message. If multiple -m options are given, their values are concatenated as separate paragraphs."			
echo -e "\t${bold}-dry-run:${reset} \t Do not create a commit, but show a list of paths that are to be committed, paths with local changes that will be left uncommitted and paths that are untracked."			

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
