#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)


echo "This is the git ${bold}fetch${reset} command."

# The command's name
echo -e 'git fetch'

# the command's description
echo "Download objects and refs from another repository"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git fetch [OPTIONS]${reset}"
echo -e "\t${bold}--all${reset}:\t Fetch all remotes."
echo -e "\t${bold}--depth=<depth>${reset}:\t Limit fetching to the specified number of commits from the tip of each remote branch history"
echo -e "\t${bold}--dry-run${reset}:\t Show what would be done, without making any changes."

echo "------------"


# the command's usage examples
# example 1
echo "git fetch origin"
echo "Updates all the remote tracking branches but does not merge them."

# example 2
echo "git fetch git://git.kernel.org/pub/scm/git/git.git feature"
echo "Fetches the branch named 'feature' from the specified URL."


exit 0
