#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the git ${bold}init${reset} command."

# The command's name
echo -e 'git init'

# the command's description
echo "Creates an empty Git repository or initializes an existing one by creating a .git directory with subdirectories for objects, refs/heads, refs/tags, and template files."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git init"
echo "It initializes an empty Git repository in the current working directory"

# example 2
echo "git init --bare"
echo "It initializes a Git 'bare' repository. A Bare repository is generally known as a 'central' repository. In practice, Git treats the current directory as the .git directory"

 


exit 0
