#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the git ${bold}merge${reset} command."

# The command's name
echo -e 'git merge'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git merge [OPTIONS]...${reset}"
echo "${bold}git merge <msg> HEAD <commit>...${reset}"	
echo -e "\t${bold}--commit, --no-commit:${reset} \t Perform the merge and commit the result. This option can be used to override --no-commit."			
echo -e "\t${bold}--progress, --no-progress:${reset} \t Turn progress on/off explicitly. If neither is specified, progress is shown if standard error is connected to a terminal. Note that not all merge strategies may support progress reporting."			
echo -e "\t${bold}--abort:${reset} \t Abort the current conflict resolution process, and try to reconstruct the pre-merge state."			

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
