#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}pull${reset} command."

# The command's name
echo -e 'git pull'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echc "Syntax:"
echo "${bold}git pull [OPTIONS] [<repository>]${reset}" 
echo -e "\t${bold}--all${reset}:\t Push all of your local branches to the specified remote" 
echo -e "\t${bold}--tags${reset}:\t The --tags flag sends all of your local tags to the remote repository"

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
