#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the git ${bold}pull${reset} command."

# The command's name
echo -e 'git pull'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git pull"
echo "Updates your remote tracking branches and merges the corresponding one with your current branch."

# example 2
echo "git pull origin master"
echo "Merges the master branch from the remote into your current branch"


exit 0
