#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}push${reset} command."

# The command's name
echo -e 'git push'

# the command's description
echo "Used to synchronize local changes with the remote repository. This is how you remotely share your code with other collaborators. If no arguments are specified, the got config is consulted to retrieve default addresses of origin and master."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git [OPTION]...[alias] [branch]${reset}"
echo -e "\t-${bold}--all:${reset} \t push all branches"			
echo -e "\t-${bold}--prune:${reset} \t remove remote branches that don’t have a local counterpart"			
echo -e "\t-${bold}-f, --force:${reset} \t the command update a remote ref that is not an ancestor of the local ref used to overwrite it"			
echo -e "\t-${bold}-u, --set-upstream:${reset} \t For every branch that is up to date or successfully pushed, add upstream (tracking) reference"			
echo -e "\t-${bold}--help:${reset} \t display this help and exit"					
echo -e "\t-${bold}--version:${reset} \t output version information and exit"	

echo "------------"

# the command's usage examples
# example 1
echo "git push -u origin <branchname>"
echo "It pushes the branch <${bold}branchname${reset}> to \“origin\” and sets tracking (an upstream link). The ${bold}-u${reset} flag ensures that whenever changes happen on \"origin\", such as when a collaborator pushes changes that you don’t have locally, Git will notify you of those changes"

# example 2
echo "git push origin ${bold}:${reset}<branchname>"
echo "It removes the branch <${bold}branchname${reset}> of the \"origin\". The special colon character ${bold}:${reset} says to Git that you want to remove that branch"


exit 0
