#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)


echo "This is the git ${bold}reset${reset} command."

# The command's name
echo -e 'git reset'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo -e "\t${bold}git reset [<mode>] [<commit>]${reset}"
echo -e "\t${bold}--soft${reset}:\t Does not touch the index file or the working tree at all (but resets the head to <commit>)"
echo -e "\t${bold}--mixed${reset}:\t Resets the index but not the working tree"
echo -e "\t${bold}--hard${reset}:\t Resets the index and working tree. Any changes to tracked files in the working tree since <commit> are discarded."

echo "------------"

# the command's usage examples
# example 1
echo "git reset HEAD^"
echo "Makes the master point to the previous commit."

# example 2
echo "git reset myfile.txt"
echo "Takes whatever myfile.txt looks like in HEAD and places it in the index, essentially unstaging the file."


exit 0
