#!/usr/bin/bash
echo "This is a git test command."

# The command's name
echo -e 'git reset'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git reset HEAD^"
echo "Makes the master point to the previous commit."

# example 2
echo "git reset myfile.txt"
echo "Takes whatever myfile.txt looks like in HEAD and places it in the index, essentially unstaging the file."


exit 0
