#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the git ${bold}rm${reset} command."

# The command's name
echo -e 'git rm'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git rm *.txt"
echo "Removes all .txt files from the current directory."

# example 2
echo "git -rf /dir"
echo "Recursively deletes all files and subdirectries in /dir if they are not up-to-date with your last checked out commit."


exit 0
