#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}rm${reset} command."

# The command's name
echo -e 'git rm'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git rm [OPTIONS]${reset}"
echo -e "\t-${bold}f${reset}:\t Override the up-to-date check."
echo -e "\t-${bold}n${reset}:\t Don’t actually remove any file(s). Show if they exist in the index and would otherwise be removed by the command"
echo -e "\t-${bold}r${reset}:\t Allow recursive removal when a leading directory name is given."

echo "------------"

# the command's usage examples
# example 1
echo "git rm *.txt"
echo "Removes all .txt files from the current directory."

# example 2
echo "git -rf /dir"
echo "Recursively deletes all files and subdirectries in /dir if they are not up-to-date with your last checked out commit."


exit 0
