#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the git ${bold}status${reset} command."

# The command's name
echo -e 'git status'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}git status [OPTIONS]${reset}"
echo -e "\t${bold}-s${reset}:\t Give the output in the short-format"
echo -e "\t${bold}-b${reset}:\t Show the branch and tracking info even in short-format"
echo -e "\t${bold}-u[<mode>]${reset}:\t The mode parameter is used to specify the handling of untracked files"

echo "------------"

# the command's usage examples
# example 1
echo "git status"
echo "Displays changes in tracked files between the working tree and the HEAD commit. Also displays a list of untracked paths."

# example 2
echo "git status --porcelain"
echo "Gives the same output as above in a format that's easy to parse for scripts."


exit 0
