#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}alias${reset} command."

# The command's name
echo -e 'alias'

# the command's description
echo "Used to customize the shell user interface. With ${bold}alias${reset}, you can assign shortcuts for commonly used commands to improve typing efficiency. Aliases persist for the current session and can be loaded by editing the shell's .rc file."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
