#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}cd${reset} command."

# The command's name
echo -e 'cd'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "cd [-L|-P] [dir]"
echo -e "\tdir: change the current directory to [dir]"
echo -e "\t-L: force symbolic links to be followed"
echo -e "\t-P: use the physical directory structure without following symbolic links"
echo -e "The default is to follow symbolic links, as if `-L' were specified."

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
