#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}chmod${reset} command."

# The command's name
echo -e 'chmod'

# the command's description
echo "Used to change file access permissions"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}chmod [OPTION]... MODE[,MODE]... FILE...${reset}"
echo "${bold}chmod [OPTION]... OCTAL-MODE FILE...${reset}"
echo "${bold}chmod [OPTION]... --reference=RFILE FILE...${reset}"
echo -e "\t${bold}-c, --changes:${reset} \t like verbose but report only when a change is made"			
echo -e "\t${bold}-f, --silent, --quiet:${reset} \t suppress most error messages"			
echo -e "\t${bold}-R, --recursive:${reset} \t change files and directories recursively"	

echo "------------"

# the command's usage examples
# example 1
echo "chmod u+x test"
echo "add the execution permission (x) for the owner (u) to a particular file/directory (in this case 'test')"

# example 2
echo "chmod -R 755 test/"
echo "apply the permission to all the files under a directory recursively (in this case 'test')"

exit 0
