#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}clear${reset} command."

# The command's name
echo "${bold}clear${reset} - clear the terminal screen"

# the command's description
echo "${bold}clear${reset} clears your screen if this is possible."
echo "It looks in the environment for the terminal type and then in the terminfo database to figure out how to clear the screen."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "clear"

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
