#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}cp${reset} command."

# The command's name
echo -e 'cp'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "cp myfile.txt /Documents"
echo "Copies myfile.txt to /Documents."

# example 2
echo "cp -R /Documents/manuals/* /Guides"
echo "Recursively copy all files and subdirectories of /Documents/manuals into /Guides."


exit 0
