#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}cp${reset} command."

# The command's name
echo -e 'cp'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "${bold}cp [OPTION]... SOURCE DEST${reset}"
echo "${bold}cp [OPTION]... SOURCE... DIRECTORY${reset}”
echo -e "\t-${bold}f${reset}, -${bold}force${reset}: if an existing destination file cannot be opened, remove it and try again"
echo -e "\t-${bold}i${reset}, --${bold}interactive${reset}: prompt before overwrite"
echo -e "\t-${bold}H${reset}: follow command-line symbolic links"


echo "------------"

# the command's usage examples
# example 1
echo "cp myfile.txt /Documents"
echo "Copies myfile.txt to /Documents."

# example 2
echo "cp -R /Documents/manuals/* /Guides"
echo "Recursively copy all files and subdirectories of /Documents/manuals into /Guides."


exit 0
