#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}curl${reset} command."

# The command's name
echo -e 'curl'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}curl [options]${reset} [URL...]"
echo -e "\t${bold}-a/--append${reset}\t (FTP)  When used in an FTP upload, this will tell curl to append to the target file instead  of overwriting it"
echo -e "\t${bold}-A/--user-agent <agent string>${reset}\t (HTTP) Specify the User-Agent string to send to the HTTP server."
echo -e "\t${bold}-b/--cookie <name=data>${reset}\t (HTTP) Pass the data to the HTTP server as a cookie."
echo -e "\t${bold}--ciphers <list of ciphers>${reset}\t (SSL) Specifies which ciphers to use in the connection."
echo -e "\t${bold}--url <URL>${reset}\t Specify a URL to fetch"

echo "------------"

# the command's usage examples
# example 1
echo "curl http://slashdot.org/index.html"
echo "Fetches the file index.html from the SlashDot website and prints it on the screen."

# example 2
echo "curl -O http://slashdot.org/index.html"
echo "Fetches the same file as above but outputs the result into a file of the same name, created in the present working directory."


exit 0
