#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}echo${reset} command."

# The command's name
echo -e 'echo'

# the command's description
echo "echo displays a line of text"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}echo [OPTION]... [STRING]...${reset}"
echo -e "-${bold}n${reset}: \t do not output the trailing newline"
echo -e "-${bold}e${reset}: \t enable interpretation of the backslash-escaped characters"
echo -e "-${bold}E${reset}: \t disable interpretation of those sequences in STRINGs"

echo "------------"

# the command's usage examples
# example 1
echo "echo 'Hello world!'"
echo "Prints 'Hello world!' on the screen."

# example 2
echo "echo -e 'Hello\tworld!'"
echo "Prints 'Hello   world!' on the screen as command escaping is enabled and '\t' represents a tab."


exit 0
