#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}echo${reset} command."

# The command's name
echo -e 'echo'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "echo 'Hello world!"
echo "Prints 'Hello world!' on the screen."

# example 2
echo "echo -e 'Hello\tworld!'"
echo "Prints 'Hello   world!' as the -e flag enables the interpretation of the tab escape sequence."


exit 0
