#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}exit${reset} command."

# The command's name
echo -e 'exit'

# the command's description
echo "Causes the shell to exit. If there are processes running in the background, the shell will remind you that they are running and simply return you to the command prompt. In this case, issuing ${bold}exit${reset} again will terminate those jobs and exit the shell."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "exit"
echo "Causes the shell to exit with the default exit code ${bold}0${reset}"

# example 2
echo "exit 1"
echo "Causes the shell to exit with the exit code ${bold}1${reset}"


exit 0
