#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}find${reset} command."

# The command's name
echo -e 'find'

# the command's description
echo "Find searches the directory tree of a filesystem, matches files to user-specified criteria and applies an action on the matched files. By default, find returns a list of files in the present working directory."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "find . -perm 755"
echo "Starting from the current working directory ${bold}.${reset}, it finds all files with specific permissions (755 in this example)"

# example 2
echo "find / -name '[a-zA-Z]*-[0-9].md' -print"
echo "Starting from the root directory ${bold}/${reset}, it finds all files whose name contains a specific pattern (in this example file names like abc-1.md or ABC-1.md, etc.), via regular expressions. The path of the file is not matched with the -${bold}name${reset} option"


exit 0
