#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}find${reset} command."

# The command's name
echo -e 'find'

# the command's description
echo "Find searches the directory tree of a filesystem, matches files to user-specified criteria and applies an action on the matched files. By default, find returns a list of files in the present working directory."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}find [-H] [-L] [-P] [-D debugopts] [-Olevel] [starting-point...] [expression]"

echo -e "\t-${bold}-P:${reset} \t Never follow symbolic links.When find examines or prints information a file, and the file is a symbolic link, the information used shall be taken from the properties of the symbolic link itself"			
echo -e "\t-${bold}-L:${reset} \t Follow symbolic links.  When find examines or prints information about files, the information used shall be takenfrom the properties of the file to which the link points, not from the link itself"	
echo -e "\t-${bold}-H:${reset} \t  Do not follow symbolic links, except while processing thecommand line arguments."
echo -e "\t-${bold}-D:${reset} \t Print diagnostic information; this can be helpful to diagnose problems with why find is not doing what you want."
echo -e "\t-${bold}-Olevel:${reset} \t Enables query optimisation"
echo -e "\t-${bold--help:${reset} \t display this help and exit"					
echo -e "\t-${bold}--version:${reset} \t output version information and exit"	


echo "------------"


# the command's usage examples
# example 1
echo "find . -perm 755"
echo "Starting from the current working directory ${bold}.${reset}, it finds all files with specific permissions (755 in this example)"

# example 2
echo "find / -name '[a-zA-Z]*-[0-9].md' -print"
echo "Starting from the root directory ${bold}/${reset}, it finds all files whose name contains a specific pattern (in this example file names like abc-1.md or ABC-1.md, etc.), via regular expressions. The path of the file is not matched with the -${bold}name${reset} option"


exit 0
