#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}for${reset} command."

# The command's name
echo -e 'for'

# the command's description
echo "The ${bold}for${reset} command is a programming construct, used to iterate through items in a list or an Array, one at a time until you reach the end."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "for ITEM in LIST"
echo "do"
echo -e "\tSOME_COMMAND(S)"
echo "done"

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
