#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}for${reset} command."

# The command's name
echo -e 'for'

# the command's description
echo "The ${bold}for${reset} command is a programming construct, used to iterate through items in a list or an Array, one at a time until you reach the end."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "for ITEM in LIST"
echo "do"
echo -e "\tSOME_COMMAND(S)"
echo "done"

echo "------------"

# the command's usage examples
# example 1
echo "i=1"
echo "for day in Mon Tue Wed Thu Fri"
echo "do"
echo "Weekday $((i++)) : $day"
echo "done"
echo "the list of values (Mon, Tue, Wed, Thu and Fri) are directly given after the keyword “in” in the bash for loop"

# example 2
echo "for (( i=1; i <= 5; i++ ))"
echo "do"
echo "Random number $i: $RANDOM"
echo "done"

echo "generates 5 random number using the bash C-style for loop"


exit 0
