#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}grep${reset} command."

# The command's name
echo -e 'grep'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}grep [OPTIONS] PATTERN [FILE...]${reset}"			
echo -e "\t${bold}-i, --ignoore-case:${reset} \t Ignore case distinctions in both the PATTERN and the input files. (-i is specified by POSIX .)"			
echo -e "\t${bold}-w, --word-regex:${reset} \t Select only those lines containing matches that form whole words. The test is that the matching substring must either be at the beginning of the line, or preceded by a non-word constituent character. Similarly, it must be either at the end of the line or followed by a non-word constituent character. Word-constituent characters are letters, digits, and the underscore."			
echo -e "\t${bold}-R, -r, --recursive${reset} \t Read all files under each directory, recursively; this is equivalent to the -d recurse option."			

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
