#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}ls${reset} command."

# The command's name
echo -e 'ls'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
echo "ls"
echo "display the contents of the current directory"

echo "ls -l"
echo "display the content of the current working directory using a long listing format"

echo "ls -la"
echo "display the content of the current working directory and include directory entries whose names begin with a dot (.)"

echo "ls -l /dir"
echo "display the content of the directory ${bold}dir${reset} using a long listing format"

echo "ls -lR /dir"
echo "display the content of the directory ${bold}dir${reset} and all its subdirectories recursively using a long listing format"

echo "ls -lh"
echo "display the content of the current working directory using a long listing format and print file sizes in human readable format (e.g., 1K 234M 2G)"

echo "ls -i"
echo "display the content of the current working directory and print the index number of each file"

echo "ls -lS"
echo "display the content of the current working directory sorted by file size"

exit 0
