#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}ls${reset} command."

# The command's name
echo -e 'ls'

# the command's description
echo "${bold}ls${reset} is a command to list files in a directory. It is specified by POSIX and the Single UNIX Specification. When invoked without any arguments, ls lists the files in the current working directory."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}ls [OPTION]...[file|dir]"
echo -e "\t-${bold}-a: \t list all files including hidden file starting with '.'"
echo -e "\t-${bold}-l: \t list with long format - show permissions"
echo -e "\t-${bold-s:\t list file size "
echo -e "\t-${bold-S:\t sort by file size "
echo -e "\t-${bold-t:\t sort by time & date "
echo -e "\t-${bold-r:\t list in reverse order "
echo -e "\t-${bold-ls:\t list with long format with file size "
echo -e "\t-${bold-la:\t list long format including hidden files "

echo "------------"

# the command's usage examples

echo "ls -lR /dir"
echo "It shows (recursively) the content of the directory ${bold}dir${reset} and all its subdirectories using a long listing format"
echo "ls -lh"
echo "It shows the content of the current working directory using a long listing format and print file sizes in human readable format (e.g., 1K 234M 2G)"
echo "ls -ltr"
echo "It shows latest modification file or directory date as last. (Reverse Output Order)"
echo "ls -n"
echo "It shows the UID and GID of files and directories in the current working directory" 

exit 0
