#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}man${reset} command."

# The command's name
echo -e 'man'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "man mv"
echo "View the manual for the mv command."

# example 2
echo "man -fK more"
echo "Search for the short description of the more command (if available) in all the man pages. It is a brute force search and will likely take some time."


exit 0
