#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}man${reset} command."

# The command's name
echo -e 'man'

# the command's description
echo "Short for Manual, man is a Unix and Linux command to display the manual of a command. For example, at the Linux prompt typing \"man ls\" would display the manual for the ls command"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}man [OPTIONS]... COMMANDNAME${reset}"
echo -e "\t${bold}-C file${reset}, ${bold}--config-file=file${reset}: \t Use configuration file file rather than the default of ~/.manpath."
echo -e "\t${bold}-k${reset}, ${bold}--apropos${reset}: \tSearch the short manual page descriptions for keywords and display any matches."
echo -e "\t${bold}-K${reset}, ${bold}--global-apropos${reset}:\tSearch for text in all manual pages. This is a brute-force search, and is likely to take some time."

echo "------------"

# the command's usage examples
# example 1
echo "man mv"
echo "View the manual for the mv command."

# example 2
echo "man -fK more"
echo "Search for the short description of the more command (if available) in all the man pages. It is a brute force search and will likely take some time."


exit 0
