#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}mkdir${reset} command."

# The command's name
echo -e 'mkdir'

# the command's description
echo "Short for ${bold}M${reset}ake ${bold}D${reset}irectory. Used to create directories on a file system if they do not exist."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}mkdir [OPTION]...DIRECTORY ... ${reset}"
echo -e "\t-${bold}-m, --mode=MODE:${reset} \t set file mode(as with command)"			
echo -e "\t-${bold}-p, --parents:${reset} \t create parent directories as necessary. When this option is used, no error is reported if a specified DIRECTORY already exists."			
echo -e "\t-${bold}-v, --verbose:${reset} \t verbose output; print a message for each created directory"					
echo -e "\t-${bold}-Z, --context=CTX:${reset} \t set the SELinux security context of each created directory to the context CTX"	
echo -e "\t-${bold}--help:${reset} \t display this help and exit"					
echo -e "\t-${bold}--version:${reset} \t output version information and exit"	


echo "------------"

# the command's usage examples
# example 1
echo "mkdir -m 755 test"
echo "Creates a new directory called 'test' and sets its access permissions to 755 (rwxr-xr-x)"

# example 2
echo "mkdir -p dir1/dir2/dir3"
echo "Throws no error if existing and makes parent directories as needed. In this example, The previous example creates /dir3 inside /dir2, inside /dir1" 


exit 0
