#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}mkdir${reset} command."

# The command's name
echo -e 'mkdir'

# the command's description
echo "Short for ${bold}M${reset}ake ${bold}D${reset}irectory. Used to create directories on a file system if they do not exist."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "mkdir -m 755 test"
echo "Creates a new directory called 'test' and sets its access permissions to 755 (rwx-r-xr-x)"

# example 2
echo "mkdir -p dir1/dir2/dir3"
echo "Throws no error if existing and makes parent directories as needed. In this example, The previous example creates /dir3 inside /dir2, inside /dir1" 


exit 0
