#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}more${reset} command."

# The command's name
echo -e 'more'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}more${reset} [${bold}-dlfpcsu${reset}] [${bold}-num${reset}] [+/ pattern] [+ linenum] [file ...]"
echo -e "\t{$bold}-d${reset}\tWhen an illegal key is pressed, ${bold}more${reset} will prompt the user instead of ringing the bell."
echo -e "\t{$bold}-l${reset}\tUsually treats ^L (form feed) as a special character, and will pause after any line that contains it.  The -l option will prevent this behavior."
echo -e "\t${bold}-c${reset}\tDo not scroll. Paint each screen from the top, clearing the remainder of each line as it is displayed"
echo -e "\tThe ${bold}+/${reset} option specifies a string that will be searched for before each file is displayed."

echo "------------"

# the command's usage examples
# example 1
echo "more -d myfile.txt"
echo "Displays the contents of myfile.txt and prompts the user with the message '[Press space to continue, 'q' to quit.]'"

# example 2
echo "more +/'test' myfile.txt"
echo "Display the contents of myfile.txt, beginning at the first line containing the string 'test'."


exit 0
