#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}more${reset} command."

# The command's name
echo -e 'more'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "more -d myfile.txt"
echo "Displays the contents of myfile.txt and prompts the user with the message '[Press space to continue, 'q' to quit.]'"

# example 2
echo "more +/'test' myfile.txt"
echo "Display the contents of myfile.txt, beginning at the first line containing the string 'test'."


exit 0
