#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}mv${reset} command."

# The command's name
echo -e 'mv'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "mv myfile.txt ../"
echo "Moves myfile.txt to its parent directory."

# example 2
echo "mv -n myfile.txt /Documents"
echo "Moves myfile.txt to the Documents folder and does not rewrite the file if it already exists."


exit 0
