#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}mv${reset} command."

# The command's name
echo -e 'mv'

# the command's description
echo "mv renames file SOURCE to DEST, or moves the SOURCE file (or files) to DIRECTORY"

echo "------------"

# the command's syntax
echo "Syntax:"
echc "${bold}mv [OPTION]... SOURCE DEST${reset}"
echo "${bold}mv [OPTION]... SOURCE... DIRECTORY${reset}"
echo "${bold}mv [OPTION]... --target-directory=DIRECTORY SOURCE...${reset}"
echo -e "\t${bold}-f${reset}, ${bold}--force${reset}: do not prompt before overwriting""
echo -e "\t${bold}-i${reset}, ${bold}--interactive${reset}: prompt before overwrite"
echo -e "\t${bold}--backup${reset}[=CONTROL]: make a backup of each existing destination file"

echo "------------"

# the command's usage examples
# example 1
echo "mv myfile.txt ../"
echo "Moves myfile.txt to its parent directory."

# example 2
echo "mv -n myfile.txt /Documents"
echo "Moves myfile.txt to the Documents folder and does not rewrite the file if it already exists."


exit 0
