#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}ping${reset} command."

# The command's name
echo -e 'ping'

# the command's description
echo "ping uses the ICMP protocol’s mandatory ECHO_REQUEST datagram to elicit an ICMP ECHO_RESPONSE from a host or gateway."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}ping [OPTIONS]... destination[options]${reset}"			
echo -e "\t${bold}-c count:${reset} \t Stop after sending count ECHO_REQUEST packets. With deadline option, ping waits for count ECHO_REPLY packets, until the timeout expires."			
echo -e "\t${bold}-v:${reset} \t Verbose output."			
echo -e "\t${bold}-i interval:${reset} \t Wait interval seconds between sending each packet. The default is to wait for one second between each packet normally, or not to wait in flood mode. Only super-user may set interval to values less 0.2 seconds."			

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
