#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}pipe${reset} command."

# The command's name
echo -e '|'

# the command's description
echo "Piping is used to feed the output of one program as the input of another. The program on the left oof the pipe symbol will produce the input for the program on the right. It is possible to chain pipes to include as many programs as desired."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ls | grep A"
echo "Lists the current working directory and pipes the result into the grep command. It shows all files containing the character A"

# example 2
echo "ls | grep -i p | wc -w"
echo "Lists the current working directory and pipes the result into the grep command and finally it pipes the grep's result into the wc command. It shows the number of words contained in the grep's result" 


exit 0
