#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}pipe${reset} command."

# The command's name
echo -e '|'

# the command's description
echo "Piping is used to feed the output of one program as the input of another. The program on the left oof the pipe symbol will produce the input for the program on the right. It is possible to chain pipes to include as many programs as desired."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
