#!/usr/bin/bash


bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo -e "This is the ${bold}pwd${reset} command. (${bold}P${reset}rint ${bold}W${reset}orking ${bold}D${reset}irectory)"

# The command's name
echo -e 'pwd'

# the command's description
echo -e "The ${bold}pwd${Reset} command shows you the absolute pathname of your current working directory. \n\nThe path starts at '/', the root, and follows the filesystem until it reaches your current location."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}pwd [OPTION]...${reset}"
echo -e "\t-${bold}-L, --logical:${reset} \t use PWD from environment, even if it contains symlinks"			
echo -e "\t-${bold}-P, --physical:${reset} \t avoid all symlinks"			
echo -e "\t-${bold}--help:${reset} \t display this help and exit"					
echo -e "\t-${bold}--version:${reset} \t output version information and exit"	

echo "------------"

# the command's usage examples
# example 1
echo "pwd -P"
echo "Display the physical current working directory (all symbolic links resolved)"

# example 2
echo "$PWD $OLDPWD"
echo "To print the current working directory (PWD) and the previous working directory (OLDPWD) as set by the cd command"

exit 0
