#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}ssh${reset} command."

# The command's name
echo -e 'ssh'

# the command's description
echo "Used to start up the SSH program which allow the user to log in to a remote machine and execute commands on it. SSH is the most common way to access remote UNIX servers securely."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "ssh -p 1234 username@remote_host"
echo "It uses the provided ${username}username${reset} and tries to set up a connection on port 1234 to the ${username}remote_host${reset} (an IP address or a domain name)" 

# example 2
echo "cat file | ssh -c -p 1234 -e none remote_host 'cat > file' 
echo "It tries to copy a compressed (${bold}-c${reset} flag) local file onto a remote_host trying to set up a connection on port 1234"


exit 0
