#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}sudo${reset} command."

# The command's name
echo -e 'sudo'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "sudo more myfile.txt"
echo "List the contents of myfile.txt as the superuser."

# example 2
echo "sudo -u greg ls"
echo "List the contents of the present working directory as user 'greg'."


exit 0
