#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}sudo${reset} command."

# The command's name
echo -e 'sudo'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}sudo -K │ -L │ -V │ -h │ -k │ -l │ -v${reset}"
echo -e "\t${bold}-H${reset}:\t sets the HOME environment variable to the homedir of the target user (root by default)"
echo -e "\t${bold}-b${reset}:\t tells sudo to run the given command in the background"
echo -e "\t${bold}-c${reset}:\t causes sudo to run the specified command with resources limited by the specified login class"

echo "------------"

# the command's usage examples
# example 1
echo "sudo more myfile.txt"
echo "List the contents of myfile.txt as the superuser."

# example 2
echo "sudo -u greg ls"
echo "List the contents of the present working directory as user 'greg'."


exit 0
