#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}tar${reset} command."

# The command's name
echo -e 'tar'

# the command's description
echo "Used to store and extract files from an archive file known as a ${bold}tarfile${reset}"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}tar [OPTION...] [FILE]...${reset}"			
echo -e "\t${bold}-c, --create:${reset} \t create a new archive"			
echo -e "\t${bold}-v, --verbose:${reset} \t verbosely list files processed"			
echo -e "\t${bold}-f, --file=ARCHIVE${reset} \t use archive file or device ARCHIVE"			

echo "------------"

# the command's usage examples
# example 1
echo "tar -cvf test.tar /home/test/"
echo  "creates a tar archive file test.tar for a directory /home/test in current working directory"

# example 2
echo "tar --extract --file=test.tar /home/test/test.php"
echo "extracts a single file called test.php from the file test.tar"


exit 0
