#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}touch${reset} command."

# The command's name
echo -e 'touch'

# the command's description
echo "The touch command is used to update the access and modification times of a specific FILE. If the file does not exists, it creates it."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}touch [OPTION]... FILE...${reset}"			
echo -e "\t-${bold}-a:${reset} \t change only the access time"			
echo -e "\t-${bold}-c, --no-create:${reset} \t do not create any files"			
echo -e "\t-${bold}-m:${reset} \t change only the modification time"			
echo "------------"

# the command's usage examples
# example 1
echo "touch test"
echo "create an empty file"

# example 2
echo "touch -c -t 03101730 test"
echo "sets the access and modification date and time to a file test as 17:30 (17:30 p.m.) March 10 of the current year (2016)."


exit 0
