#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}touch${reset} command."

# The command's name
echo -e 'touch'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "touch [OPTION] FILE"
echo -e "\tFILE: Name of existing file to be opened or non-existing file that will be created."

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
