#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}variables${reset} command."

# The command's name
echo -e 'variables'

# the command's description
echo "Variables act as named locations in memory for storing useful information while running a Bash script."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}variable${reset}=${bold}value${reset}"
echo -e "\t:\${${bold}variable?word${reset}} :\t Complain if undefined"
echo -e "\t:\${${bold}variable-word${reset}} :\t Use ${bold}word${reset} as value if the ${bold}variable${reset} is undefined" 
echo -e "\t:\${${bold}variable+word${reset}} :\t Use ${bold}word${reset} as value if the ${bold}variable${reset} is defined" 
echo -e "\t:\${${bold}variable=word${reset}} :\t Set ${bold}word${reset} as the ${bold}variable${reset}'s name if is undefined" 

echo "------------"

# the command's usage examples
# example 1
echo "name=George"
echo "echo '$name' will print 'George'"

exit 0
