#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}wc${reset} command."

# The command's name
echo -e 'wc'

# the command's description
echo "Prints newline, word and byte counts for the given file. If multiple files are given, the command outputs the total of each value. If no file is passed, the command reads standard input, <STDIN>."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
