#!/usr/bin/bash

bold=$(tput bold)
underline=$(tput smul)
stop_underline=$(tput rmul)
reset=$(tput sgr0)

echo "This is the ${bold}wc${reset} command."

# The command's name
echo -e 'wc'

# the command's description
echo "Prints newline, word and byte counts for the given file. If multiple files are given, the command outputs the total of each value. If no file is passed, the command reads standard input, <STDIN>."

echo "------------"

# the command's syntax
echo "Syntax:"
echo "${bold}wc [OPTION]...[FILE]...${reset}"
echo -e "\t-${bold}-c, --bytes:${reset} \t print the byte counts"			
echo -e "\t-${bold}-m, --chars:${reset} \t print the character counts"		
echo -e "\t-${bold}-l, --lines:${reset} \t print the newline counts"			
echo -e "\t-${bold}--files0-from=F:${reset} \t read input from the files specified by NUL-terminated names in file F; If F is "-" then read names from standard input"			
echo -e "\t-${bold}-L, --max-line-length:${reset} \t print the length of the longest line"			
echo -e "\t-${bold}-w, --words:${reset} \t print the word counts"			
echo -e "\t-${bold}--help:${reset} \t display this help and exit"					
echo -e "\t-${bold}--version:${reset} \t output version information and exit"	

echo "------------"

# the command's usage examples
# example 1
echo "wc -l script.sh"
echo "Prints the newline counts inside the file 'script.sh'"

# example 2
echo "wc -w /dir/script.sh"
echo "Prints the character counts inside the file 'script.sh' located into the directory 'dir'"


exit 0
