#!/usr/bin/bash

bold=`tput bold`
underline=`tput smul`
stop_underline=`tput rmul`
reset=`tput sgr0`

echo "This is the ${bold}whoami${reset} command."

# The command's name
echo -e 'whoami'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "whoami [OPTION]..."
echo -e "\t--help: display this help and exit"
echo -e "\t--version: output version information and exit"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
